export { default as Back } from './Back'
export { default as Check } from './Check'
export { default as Discover } from './Discover'
export { default as Heart } from './Heart'
export { default as Plus } from './Plus'
export { default as Video } from './Video'